# Generated by Django 4.1.4 on 2023-03-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evening", "0026_alter_staff_soldier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cons_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Номер"
                    ),
                ),
                (
                    "cons_date",
                    models.DateField(
                        blank=True, default="2000-01-01", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "cons_status",
                    models.BooleanField(default=True, verbose_name="Приходна накладна"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goods_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "goods_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Фамілія"
                    ),
                ),
                (
                    "life_time",
                    models.DurationField(default=365, verbose_name="Строк служби"),
                ),
                (
                    "goods_unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Служба"
                    ),
                ),
                (
                    "goods_description",
                    models.TextField(max_length=255, verbose_name="Опис"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Найменування служби",
                    ),
                ),
                (
                    "service_comm",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Начальник"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_quantity", models.IntegerField(verbose_name="Кільксть")),
                (
                    "goods_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="material.goods",
                        verbose_name="Найменування",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseToSoldiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, default="2000-01-01", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "release_goods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="material.goods",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "soldier_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="evening.soldiers",
                        verbose_name="Військовослужбовець",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsignmentGoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Кількість")),
                (
                    "consignmen_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="material.consignment",
                        verbose_name="Накладна",
                    ),
                ),
                (
                    "goods_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="material.goods",
                        verbose_name="Товар",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consignment",
            name="cons_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="material.service",
                verbose_name="Служба",
            ),
        ),
    ]
