# Generated by Django 4.1.4 on 2023-03-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consignmentgoods",
            old_name="consignmen_ref",
            new_name="consignment_ref",
        ),
        migrations.AlterField(
            model_name="goods",
            name="goods_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Найменування"
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="goods_unit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Один. виміру"
            ),
        ),
    ]
