# Generated by Django 4.1.4 on 2023-03-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "material",
            "0002_rename_consignmen_ref_consignmentgoods_consignment_ref_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consignmentgoods",
            name="consignment_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="material.consignment",
                verbose_name="Накладна",
            ),
        ),
    ]
