# Generated by Django 4.1.4 on 2023-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0003_alter_consignmentgoods_consignment_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="goods_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Артикул",
            ),
        ),
    ]
