# Generated by Django 4.1.4 on 2023-02-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(max_length=255, verbose_name='Фамілія')),
                ('name', models.TextField(max_length=255, verbose_name='Імʼя')),
                ('fathers_name', models.TextField(max_length=255, verbose_name='По батькові')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Код посади')),
                ('position_name', models.TextField(max_length=255, verbose_name='Посада')),
                ('mil_prof', models.TextField(max_length=255, verbose_name='ВОС')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evening.soldiers', unique=True, verbose_name='Військовослужбовець')),
            ],
        ),
    ]
