# Generated by Django 4.1.4 on 2023-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffplan',
            name='position_rank',
            field=models.CharField(default='soldier', max_length=50, verbose_name='Звання посади'),
            preserve_default=False,
        ),
    ]
