# Generated by Django 4.1.4 on 2023-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0002_staffplan_position_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldiers',
            name='fathers_name',
            field=models.CharField(max_length=255, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='staffplan',
            name='mil_prof',
            field=models.CharField(max_length=50, verbose_name='ВОС'),
        ),
        migrations.AlterField(
            model_name='staffplan',
            name='position_name',
            field=models.CharField(max_length=50, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='staffplan',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код посади'),
        ),
    ]
