# Generated by Django 4.1.4 on 2023-02-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0003_alter_soldiers_fathers_name_alter_soldiers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffplan',
            name='soldier',
            field=models.IntegerField(),
        ),
    ]
