# Generated by Django 4.1.4 on 2023-02-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0004_alter_staffplan_soldier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffplan',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evening.soldiers', unique=True, verbose_name='Військовослужбовець'),
        ),
    ]
