# Generated by Django 4.1.4 on 2023-02-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0005_alter_staffplan_soldier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffplan',
            name='soldier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='evening.soldiers', verbose_name='Військовослужбовець'),
        ),
    ]
