# Generated by Django 4.1.4 on 2023-02-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0006_alter_staffplan_soldier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=50, verbose_name='Наіменування зброї')),
                ('weapon_number', models.CharField(max_length=50, unique=True, verbose_name='Номер зброї')),
                ('weapon_type', models.CharField(choices=[('s', 'Стрілкова зброя'), ('m', 'Кулемет великоколіберний'), ('mr', 'Міномет'), ('g', 'Гранатомет')], max_length=50, verbose_name='Тип зброї')),
            ],
        ),
        migrations.AlterModelOptions(
            name='soldiers',
            options={'verbose_name': 'Військовослужбовець', 'verbose_name_plural': 'Військовослужбовці'},
        ),
        migrations.AlterModelOptions(
            name='staffplan',
            options={'ordering': ['slug'], 'verbose_name': 'Штатний розклад', 'verbose_name_plural': 'Штатний розклад'},
        ),
    ]
