# Generated by Django 4.1.4 on 2023-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0007_weapons_alter_soldiers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='weapon_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='weapon_type',
            field=models.CharField(choices=[('p', 'Пістолет'), ('s', 'Стрілкова зброя'), ('m', 'Кулемет великоколіберний'), ('mr', 'Міномет'), ('g', 'Гранатомет')], max_length=50, verbose_name='Тип зброї'),
        ),
    ]
