# Generated by Django 4.1.4 on 2023-02-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0008_weapons_weapon_registration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapons',
            options={'ordering': ['weapon_type', 'weapon_name'], 'verbose_name': 'Зброя підрозділу', 'verbose_name_plural': 'Зброя підрозділу'},
        ),
        migrations.AlterField(
            model_name='weapons',
            name='weapon_type',
            field=models.CharField(choices=[('p', 'Пістолет'), ('s', 'Стрілкова зброя'), ('m', 'Кулемет ручний'), ('mb', 'Кулемет великокаліберний'), ('mr', 'Міномет'), ('g', 'Гранатомет')], max_length=50, verbose_name='Тип зброї'),
        ),
        migrations.CreateModel(
            name='WeaponCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evening.soldiers', unique=True, verbose_name='Військовослужбовець')),
                ('weapon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='evening.weapons', verbose_name='Закріплена зброя')),
            ],
        ),
    ]
