# Generated by Django 4.1.4 on 2023-02-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0009_alter_weapons_options_alter_weapons_weapon_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponcard',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evening.soldiers', verbose_name='Військовослужбовець'),
        ),
    ]
