# Generated by Django 4.1.4 on 2023-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0010_alter_weaponcard_soldier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weaponcard',
            options={'ordering': ['soldier'], 'verbose_name': 'Картка зброї військовослужбовця', 'verbose_name_plural': 'Картки зброї військовослужбовців'},
        ),
        migrations.AddField(
            model_name='soldiers',
            name='callsign',
            field=models.CharField(default='call', max_length=50, verbose_name='Позивний'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='fathers_name',
            field=models.CharField(max_length=50, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамілія'),
        ),
    ]
