# Generated by Django 4.1.4 on 2023-02-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0011_alter_weaponcard_options_soldiers_callsign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiers',
            name='mil_prof',
            field=models.CharField(max_length=50, null=True, verbose_name='ВОС'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='position_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='position_rank',
            field=models.CharField(max_length=50, null=True, verbose_name='Звання посади'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Код посади'),
        ),
        migrations.AlterField(
            model_name='staffplan',
            name='mil_prof',
            field=models.CharField(max_length=50, null=True, verbose_name='ВОС'),
        ),
        migrations.AlterField(
            model_name='staffplan',
            name='position_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='staffplan',
            name='position_rank',
            field=models.CharField(max_length=50, null=True, verbose_name='Звання посади'),
        ),
        migrations.AlterField(
            model_name='staffplan',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Код посади'),
        ),
    ]
