# Generated by Django 4.1.4 on 2023-02-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0012_soldiers_mil_prof_soldiers_position_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='soldiers',
            options={'ordering': ['slug'], 'verbose_name': 'Військовослужбовець', 'verbose_name_plural': 'Військовослужбовці'},
        ),
        migrations.DeleteModel(
            name='StaffPlan',
        ),
        migrations.AddField(
            model_name='soldiers',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='evening.ranks'),
        ),
    ]
