# Generated by Django 4.1.4 on 2023-02-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0013_ranks_alter_soldiers_options_delete_staffplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiers',
            name='addres',
            field=models.CharField(max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='blood_type',
            field=models.CharField(max_length=10, null=True, verbose_name='Группа крові'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='tax_number',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='ІПН'),
        ),
        migrations.AddField(
            model_name='weapons',
            name='year_manufacture',
            field=models.DateField(null=True, verbose_name='Рік виготовлення'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='evening.ranks', verbose_name='Звання'),
        ),
    ]
