# Generated by Django 4.1.4 on 2023-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0014_soldiers_addres_soldiers_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='weapons',
            options={'ordering': ['weapon_name'], 'verbose_name': 'Зброя підрозділу', 'verbose_name_plural': 'Зброя підрозділу'},
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='weapon_type',
        ),
    ]
