# Generated by Django 4.1.4 on 2023-02-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0015_weaponstypes_alter_weapons_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='weapon_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='evening.weaponstypes', verbose_name='Тип зброї'),
        ),
    ]
