# Generated by Django 4.1.4 on 2023-02-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0016_weapons_weapon_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapons',
            options={'ordering': ['id'], 'verbose_name': 'Зброя підрозділу', 'verbose_name_plural': 'Зброя підрозділу'},
        ),
        migrations.AddField(
            model_name='soldiers',
            name='boots_s',
            field=models.IntegerField(default=0, verbose_name='Взуття'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='children',
            field=models.IntegerField(default=0, verbose_name='Діти'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='complect_center',
            field=models.CharField(max_length=255, null=True, verbose_name='Центр комплектаціі'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='head_s',
            field=models.IntegerField(default=0, verbose_name='Головний убор'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='hight_s',
            field=models.IntegerField(default=0, verbose_name='Зріст'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='mob_date',
            field=models.DateField(null=True, verbose_name='Дата мобілізаціі'),
        ),
        migrations.AddField(
            model_name='soldiers',
            name='size',
            field=models.IntegerField(default=0, verbose_name='Розмір'),
        ),
    ]
