# Generated by Django 4.1.4 on 2023-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0017_alter_weapons_options_soldiers_boots_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldiers',
            name='boots_s',
            field=models.CharField(max_length=50, null=True, verbose_name='Взуття'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='children',
            field=models.CharField(max_length=50, null=True, verbose_name='Діти'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='head_s',
            field=models.CharField(max_length=50, null=True, verbose_name='Головний убор'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='hight_s',
            field=models.CharField(max_length=50, null=True, verbose_name='Зріст'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='size',
            field=models.CharField(max_length=50, null=True, verbose_name='Розмір'),
        ),
    ]
