# Generated by Django 4.1.4 on 2023-02-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0018_alter_soldiers_boots_s_alter_soldiers_children_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapons',
            options={'ordering': ['weapon_type', 'weapon_name'], 'verbose_name': 'Зброя підрозділу', 'verbose_name_plural': 'Зброя підрозділу'},
        ),
        migrations.AddField(
            model_name='weapons',
            name='soldier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evening.soldiers', verbose_name='Закріплено'),
        ),
        migrations.DeleteModel(
            name='WeaponCard',
        ),
    ]
