# Generated by Django 4.1.4 on 2023-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0019_alter_weapons_options_weapons_soldier_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiers',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
