# Generated by Django 4.1.4 on 2023-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0020_soldiers_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldiers',
            name='passport',
            field=models.CharField(blank=True, max_length=50, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='blood_type',
            field=models.CharField(max_length=15, null=True, verbose_name='Группа крові'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
    ]
