# Generated by Django 4.1.4 on 2023-02-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0021_soldiers_passport_alter_soldiers_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammo_name', models.CharField(max_length=255, verbose_name='Найменування')),
                ('caliber', models.CharField(max_length=255, verbose_name='Калібр')),
                ('ammo_type', models.CharField(max_length=255, verbose_name='Маркування')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
    ]
