# Generated by Django 4.1.4 on 2023-03-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evening', '0022_ammo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammo',
            options={'ordering': ['quantity'], 'verbose_name': 'Боєкомплект підрозділу', 'verbose_name_plural': 'Боєкомплект підрозділу'},
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='addres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='birth_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='blood_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Группа крові'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='boots_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Взуття'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='callsign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Позивний'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='children',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Діти'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='complect_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Центр комплектаціі'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='head_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Головний убор'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='hight_s',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Зріст'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='mil_prof',
            field=models.CharField(max_length=50, verbose_name='ВОС'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='mob_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Дата мобілізаціі'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='position_name',
            field=models.CharField(max_length=50, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='position_rank',
            field=models.CharField(max_length=50, verbose_name='Звання посади'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evening.ranks', verbose_name='Звання'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код посади'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='soldiers',
            name='tax_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ІПН'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='soldier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evening.soldiers', verbose_name='Закріплено'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='year_manufacture',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Рік виготовлення'),
        ),
    ]
