# Generated by Django 4.1.4 on 2023-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evening", "0023_alter_ammo_options_alter_soldiers_addres_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Код посади")),
                (
                    "position_name",
                    models.CharField(max_length=50, verbose_name="Посада"),
                ),
                ("mil_prof", models.CharField(max_length=50, verbose_name="ВОС")),
                (
                    "position_rank",
                    models.CharField(max_length=50, verbose_name="Звання посади"),
                ),
                (
                    "soldier",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Військовослужбовець"
                    ),
                ),
            ],
        ),
    ]
