# Generated by Django 4.1.4 on 2023-03-11 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evening", "0024_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="soldiers",
            options={
                "verbose_name": "Військовослужбовець",
                "verbose_name_plural": "Військовослужбовці",
            },
        ),
        migrations.RemoveField(
            model_name="soldiers",
            name="mil_prof",
        ),
        migrations.RemoveField(
            model_name="soldiers",
            name="position_name",
        ),
        migrations.RemoveField(
            model_name="soldiers",
            name="position_rank",
        ),
        migrations.RemoveField(
            model_name="soldiers",
            name="slug",
        ),
    ]
