# Generated by Django 4.1.4 on 2023-03-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evening", "0025_alter_soldiers_options_remove_soldiers_mil_prof_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="soldier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="evening.soldiers",
                verbose_name="Військовослужбовець",
            ),
        ),
    ]
