# Generated by Django 4.1.4 on 2023-03-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evening", "0026_alter_staff_soldier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={"ordering": ("slug",), "verbose_name": "Штатний розклад"},
        ),
        migrations.AlterField(
            model_name="staff",
            name="soldier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="evening.soldiers",
                verbose_name="Військовослужбовець",
            ),
        ),
    ]
