# Generated by Django 4.1.4 on 2023-03-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evening", "0027_alter_staff_options_alter_staff_soldier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="soldier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="evening.soldiers",
                verbose_name="Військовослужбовець",
            ),
        ),
    ]
